"""Change expires_at to TIMESTAMP WITHOUT TIME ZONE

Revision ID: 034d5429b038
Revises: 27dee4214239
Create Date: 2025-08-14 22:11:51.732551

"""

from typing import Union, Sequence

# revision identifiers, used by Alembic.
revision: str = "034d5429b038"
down_revision: Union[str, Sequence[str], None] = "27dee4214239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
